#ifndef SIMPLEGPXREADER_GLOBAL_H
#define SIMPLEGPXREADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIMPLEGPXREADER_LIBRARY)
#  define SIMPLEGPXREADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIMPLEGPXREADERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMPLEGPXREADER_GLOBAL_H
